name: MarkDown Lint
on:
  pull_request:
    branches:
      - 'master'

jobs:
  md-lint:
    name: lint mds
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: md-lint
      uses: avto-dev/markdown-lint@v1
      with:
        rules: '/lint/rules/changelog.js'
        config: '/lint/config/changelog.yml'
        args: './*.md'
